### PR TITLE
Create bug_report.yml

### PR DESCRIPTION
**Pull request by Sopor**
New bug template to make users fill in all necessary information

### CODE REVIEW

**Comment by Sopor** [comment]
I believe you need to delete bug_report.md

**Comment by Sopor** [comment]
If you are going to use it i can make one for the `Feature request` too ...

**Comment by Octal450** [comment]
OK, lets try it.

**Comment by Octal450** [comment]
I like it. Please proceed with feature request.

Thanks!
Josh

**Pull request merged**
